# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Dobby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    python-version: ['3.5', '3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2

    - name: This is a build for polaris(7thMinute Project)
      run: echo Building starting for Polaris - 7thMinute Project

    - name: Check out Repo
      run: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

          - name: Build, tag, and push image to Amazon ECR Backend
            id: build-image_polaris
            env:
              ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              ECR_REPOSITORY: githubactions
              IMAGE_TAG: latest
            run: |
              # Build a docker container and
              # push it to ECR so that it can
              # be deployed to ECS.
              docker build -t 029086201010.dkr.ecr.ap-southeast-1.amazonaws.com/polaris:latest
              docker push 029086201010.dkr.ecr.ap-southeast-1.amazonaws.com/polaris:latest
              echo "::set-output name=image::029086201010.dkr.ecr.ap-southeast-1.amazonaws.com/polaris:latest"

    - name: Build completed
        run: |
          echo Build has been completed for polaris,
          echo test, and deploy your project.